In [24]:
import numpy as np
def array_factory(mode, shape, value=None):

    if mode == "zeros":
        return np.zeros((shape, shape))

    elif mode == "ones":
        return np.ones((shape, value))

    elif mode == "full":
        return np.full((shape, shape), value)

    elif mode == "identity":
        return np.eye(shape)

    else:
        raise ValueError("Invalid mode")

print(array_factory("identity", 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    

    try:
        # Convert both inputs to NumPy arrays
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Reshape the first array
        reshaped_arr1 = arr1.reshape(new_shape)

        # Vertically stack both arrays
        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")

data1 = [1, 2, 3, 4]

data2 = [[5, 6],
         [7, 8]]

result = secure_reshape_and_stack(data1, data2, (2, 2))

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
